FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm install --prefer-offline --no-audit --no-fund --legacy-peer-deps || true

COPY . .

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"
ENV WATCHPACK_POLLING true

CMD ["npm", "run", "dev"]
