"""
CrisisState — Shared type contract for the LangGraph agent swarm.

This TypedDict defines the full state object passed between all 6 agents.
Fields are populated progressively as agents execute in sequence.

Phase 3 will implement the full LangGraph state machine using this schema.
"""
from typing import TypedDict, Optional, List, Dict, Any
from datetime import datetime


class AgentFinding(TypedDict):
    """Single agent's contribution to the crisis evidence chain."""
    agent: str                  # Agent name
    confidence: float           # 0.0 - 1.0
    summary: str                # Human-readable finding
    data: Dict[str, Any]        # Raw evidence payload
    timestamp: str              # ISO 8601


class RouteRecommendation(TypedDict):
    """Alternative route generated by RouteOptimizationAgent."""
    description: str
    waypoints: List[Dict[str, float]]   # [{lat, lon}, ...]
    distance_km: float
    eta_minutes: int
    fuel_increase_pct: float
    risk_score: float                   # 0.0 - 1.0


class NormalizedEvent(TypedDict):
    source: str         # 'bmkg', 'tomtom', 'aisstream', 'nasa_firms', 'osint'
    event_type: str     # 'flood', 'congestion', 'port_closure', 'fire', 'price_spike'
    severity: str       # 'low', 'medium', 'high', 'critical'
    raw_payload: Dict[str, Any]
    validated: bool
    validation_errors: List[str]


class LTMEpisode(TypedDict):
    episode_id: str
    title: str
    description: str
    crisis_type: str
    inflation_multiplier: float
    recovery_days: int
    similarity_score: float


class GraphRAGNode(TypedDict):
    entity_id: str
    entity_type: str    # 'port', 'route', 'warehouse', 'commodity', 'supplier'
    name: str
    relation: str       # 'DEPENDS_ON', 'SHIPS_VIA', 'SUPPLIES', 'LOCATED_IN'
    impact_score: float


class CrisisState(TypedDict):
    """
    The central state object shared across all LangGraph agents.
    Stored in Redis KV (STM) for the duration of an active crisis.
    """
    # Crisis identification
    crisis_id: str
    title: str
    type: str                           # 'flood', 'port_closure', 'wildfire', 'congestion', 'earthquake'
    is_simulated: bool                  # True if triggered via TheoTown simulation

    # Location
    lat: float
    lon: float
    region: str                         # 'north_sumatra', 'java', etc.
    affected_polygon: Optional[List]    # GeoJSON polygon coordinates

    # Status tracking
    status: str                         # 'detecting', 'validating', 'validated', 'resolved'
    overall_confidence: float           # 0.0 - 1.0 (gate fires at 0.85)

    # Agent findings (populated as each agent runs)
    data_collection_finding: Optional[AgentFinding]
    osint_hazard_finding: Optional[AgentFinding]
    prediction_finding: Optional[AgentFinding]
    route_optimization_finding: Optional[AgentFinding]
    economic_intelligence_finding: Optional[AgentFinding]
    decision_support_output: Optional[str]  # Final synthesized summary

    # Route recommendations
    route_recommendations: List[RouteRecommendation]

    # Economic forecast
    inflation_forecast: Optional[Dict[str, Any]]   # {commodity, region, pct_increase, timeframe_hours}

    # GraphRAG traversal result
    causal_chain: Optional[List[Dict[str, str]]]   # [{node, relation, node}, ...]

    # New fields for Phase 3
    normalized_event: Optional[NormalizedEvent]
    hazard_polygons: Optional[List[Dict]]
    congestion_forecast: Optional[Dict[str, Any]]
    ltm_episodes: Optional[List[LTMEpisode]]
    graphrag_chain: Optional[List[GraphRAGNode]]
    consensus_breakdown: Optional[Dict[str, float]]
    validated: bool

    # Metadata
    created_at: str                     # ISO 8601
    updated_at: str                     # ISO 8601
    messages: List[str]                 # Agent communication log
